allprojects {
    repositories {
        google()          // Google's repository for Android dependencies
        mavenCentral()    // Maven Central repository for standard dependencies
       
    }
}


rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}